# MyForterro connector Infosystem default configuration

# Java project properties files directory
ZAIMFT.project.properties = java/properties

# Default properties files (authentication and default agent)
ZAIMFT.default.authentication=authenticator.properties
ZAIMFT.default.agent=agent_1.properties