# MyForterro agent configuration
#
# Fill in the following values
# Please do not change key names
#
# Timeouts are specified in milliseconds (ms)

## Agent API URL
myforterro.agent.name=
myforterro.agent.timeout.connect=15000
myforterro.agent.timeout.read=240000

myforterro.agent.url=
myforterro.agent.endpoint=
myforterro.agent.id=
