# MyForterro API Global Configuration
#
# Fill in the following values
# Please do not change key names
#

## Authentication
myforterro.token.url=

# Application credentials
myforterro.client.id=
myforterro.client.secret=
myforterro.target.application=
myforterro.target.tenant=

# Files upload URL
myforterro.files.upload.url=
myforterro.files.upload.endpoint=
